export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  console.log("Montando layout");

  return (
    <html lang="en">
      <body>
        <div id="menu">
          <nav>
            <ul>
              <li><a href="/">Início</a></li>
              <li><a href="/sobre">Sobre</a></li>
              <li><a href="/contato">Contato</a></li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
